# Kindly borrowed from https://github.com/the-dotify-project/dotify

repos:
  - repo: https://github.com/humitos/mirrors-autoflake.git
    rev: v1.3
    hooks:
      - id: autoflake
        args: ['--in-place', '--remove-all-unused-imports', '--remove-unused-variable']
  - repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 21.5b1
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: debug-statements
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.17.8
    hooks:
      - id: commitizen
        stages: [commit-msg]
